[build]
target = "index.html"

[serve]
address = "127.0.0.1"
port = 8082

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:3000/api/"

[[proxy]]
rewrite = "/auth/"
backend = "http://127.0.0.1:3000/auth/"

# [[hooks]]
# stage = "build"
# command = "cmd"
# command_arguments = ["/c", "npx", "tailwindcss", "-i", "style/input.css", "-o", "style/output.css"]
